language: ruby

notifications:
  email:
    recipients:
      - delabriere@imsb.biol.ethz.ch
    on_success: always
    on_failure: always

services:
  - docker

before_install:
  - docker build -t adelabriere/lcms_workflow_zamboni:latest .
script:
  - docker run adelabriere/lcms_worfklow_zamboni:latest -v tests/input:/input -v test/output:/output -e POLARITY=positive -e USERNAME=test lcms_worfklow_zamboni
